export const FETCH_MEMBERSHIP_CATEGORY_REQUEST =
  'FETCH_MEMBERSHIP_CATEGORY_REQUEST';
export const FETCH_MEMBERSHIP_CATEGORY_SUCCESS =
  'FETCH_MEMBERSHIP_CATEGORY_SUCCESS';
export const FETCH_MEMBERSHIP_CATEGORY_FAILURE =
  'FETCH_MEMBERSHIP_CATEGORY_FAILURE';

export const FETCH_MEMBERSHIP_PLANS_REQUEST = 'FETCH_MEMBERSHIP_PLANS_REQUEST';
export const FETCH_MEMBERSHIP_PLANS_SUCCESS = 'FETCH_MEMBERSHIP_PLANS_SUCCESS';
export const FETCH_MEMBERSHIP_PLANS_FAILURE = 'FETCH_MEMBERSHIP_PLANS_FAILURE';
