export const FETCH_MEMBERSHIP_CATEGORY_REQUEST =
  'FETCH_MEMBERSHIP_CATEGORY_REQUEST';
export const FETCH_MEMBERSHIP_CATEGORY_SUCCESS =
  'FETCH_MEMBERSHIP_CATEGORY_SUCCESS';
export const FETCH_MEMBERSHIP_CATEGORY_FAILURE =
  'FETCH_MEMBERSHIP_CATEGORY_FAILURE';

export const FETCH_MEMBERSHIP_PLANS_REQUEST = 'FETCH_MEMBERSHIP_PLANS_REQUEST';
export const FETCH_MEMBERSHIP_PLANS_SUCCESS = 'FETCH_MEMBERSHIP_PLANS_SUCCESS';
export const FETCH_MEMBERSHIP_PLANS_FAILURE = 'FETCH_MEMBERSHIP_PLANS_FAILURE';

export const GET_MEMBERSHIP_BY_ID_REQUEST = 'GET_MEMBERSHIP_BY_ID_REQUEST';
export const GET_MEMBERSHIP_BY_ID_SUCCESS = 'GET_MEMBERSHIP_BY_ID_SUCCESS';
export const GET_MEMBERSHIP_BY_ID_FAILURE = 'GET_MEMBERSHIP_BY_ID_FAILURE';

export const FETCH_MEMBERSHIP_OFFERS_REQUEST =
  'FETCH_MEMBERSHIP_OFFERS_REQUEST';
export const FETCH_MEMBERSHIP_OFFERS_SUCCESS =
  'FETCH_MEMBERSHIP_OFFERS_SUCCESS';
export const FETCH_MEMBERSHIP_OFFERS_FAILURE =
  'FETCH_MEMBERSHIP_OFFERS_FAILURE';

export const MEMBERSHIP_BOOKING_REQUEST = 'MEMBERSHIP_BOOKING_REQUEST';
export const MEMBERSHIP_BOOKING_SUCCESS = 'MEMBERSHIP_BOOKING_SUCCESS';
export const MEMBERSHIP_BOOKING_FAILURE = 'MEMBERSHIP_BOOKING_FAILURE';

export const MEMEBRSHIP_PAYMENT_REQUEST = 'MEMEBRSHIP_PAYMENT_REQUEST';
export const MEMEBRSHIP_PAYMENT_SUCCESS = 'MEMEBRSHIP_PAYMENT_SUCCESS';
export const MEMEBRSHIP_PAYMENT_FAILURE = 'MEMEBRSHIP_PAYMENT_FAILURE';

export const GET_MY_MEMBERSHIP_REQUEST = 'GET_MY_MEMBERSHIP_REQUEST';
export const GET_MY_MEMBERSHIP_SUCCESS = 'GET_MY_MEMBERSHIP_SUCCESS';
export const GET_MY_MEMBERSHIP_FAILURE = 'GET_MY_MEMBERSHIP_FAILURE';
