export const VOUCHER_REDEEM_REQUEST = 'VOUCHER_REDEEM_REQUEST';
export const VOUCHER_REDEEM_SUCCESS = 'VOUCHER_REDEEM_SUCCESS';
export const VOUCHER_REDEEM_FAILURE = 'VOUCHER_REDEEM_FAILURE';

export const RESEND_VOUCHER_VERIFY_CODE_REQUEST =
  'RESEND_VOUCHER_VERIFY_CODE_REQUEST';
export const RESEND_VOUCHER_VERIFY_CODE_SUCCESS =
  'RESEND_VOUCHER_VERIFY_CODE_SUCCESS';
export const RESEND_VOUCHER_VERIFY_CODE_FAILURE =
  'RESEND_VOUCHER_VERIFY_CODE_FAILURE';

export const CHECK_VOUCHER_REDEEMTION_REQUEST =
  'CHECK_VOUCHER_REDEEMTION_REQUEST';
export const CHECK_VOUCHER_REDEEMTION_SUCCESS =
  'CHECK_VOUCHER_REDEEMTION_SUCCESS';
export const CHECK_VOUCHER_REDEEMTION_FAILURE =
  'CHECK_VOUCHER_REDEEMTION_FAILURE';
