export const Routes = {
  OnboardingScreen: 'OnboardingScreen',
  AppEntryScreen: 'AppEntryScreen',
  HomeScreen: 'HomeScreen',
  AuthScreen: 'AuthScreen',
  Signupscreen: 'Signupscreen',
  MembershipScreen: 'MembershipScreen',
  CategoryScreen: 'CategoryScreen',
  CategoryDetail: 'CategoryDetail',
  MoreScreen: 'MoreScreen',
  UpdatesScreen: 'UpdatesScreen',
  LoadingScreen: 'LoadingScreen',
  FAQs: 'FAQs',
  EditionScreen: 'EditionScreen',
  PaymentScreen: 'PaymentScreen',
  CheckoutScreen: 'CheckoutScreen',
  MembershipSuccess: 'MembershipSuccess',
  AboutScreen: 'AboutScreen',
  ContactScreen: 'ContactScreen',
  ProfileScreen: 'ProfileScreen',
  OtpScreen: 'OtpScreen',
};
